name: GitHub Actions Practica
on: [push]
jobs: 
  Explorando-GitHub-Actions:
  runs-on: ubuntu-latest
  steps:
    - run: echo "El flujo de trabajo ha sido ejecutado en el evento: ${{ github.event_name }}"
    - run: echo "El trabajo se esta ejecutando en un servidor ${{ runner.os }} hospedado en GitHub"
    - run: echo "El nombre de la rama es: ${{ github.ref }} ha sido colonado el runner."
    name: Verifica el codigo del repositorio
      uses: actions/checkout@v2
    - run: echo "El repositorio: ${{ github.repository }} ha sido colonado al runner.*
    - run: echo " El flujo de trabajo esta listo para para verificar el código en el runner."
    - name: Listar archivos en el repositorio
    run:
      ls ${{ github.workspace }}
    -run: echo "el estado del trabaio es: ${{ job.status }}.
